### ISSUE TITLE
Add option to defer script?

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/esri-loader#16]
I've tested this, and I can't tell any difference when you add the `defer` to the script attribute when preloading, but it would be very easy to support passing that in as an option.

**Comment by davetimmins** [comment]
Would that make any difference? I thought defer was just for waiting until the page had loaded but this shouldn't be being run until then anyway so it's redundant.

**Comment by tomwayson** [comment]
Good point.

This came up b/c I was having trouble finding a single point in the [react router/component lifecycle](https://github.com/ReactTraining/react-router/blob/v3/docs/guides/ComponentLifecycle.md) to preload the JSAPI. I ended up going w/ my App components `componentWillMount`, but it still seemed to me that nothing would be rendered at that point. So I decided to compare that to just including a `<script>` tag w/ defer in the page and saw that using `esriLoader` to preload was indeed noticeably faster (when using network throttling to simulate a 3G connection).

Anyway, I thought to also try adding the `defer` attribute when preloading, but you're right, that doesn't make any sense and it didn't make any difference, so closing this for now.

**Comment by davetimmins** [comment]
For react it probably makes more sense to preload outside of the component that uses the map, so some container component. That could be included on each route too in cases where deep linking is supported.

**Comment by davetimmins** [comment]
Here's a quick example

```js
import React from 'react';
import { bootstrap, isLoaded } from 'esri-loader';

class EsriLoaderContainer extends React.PureComponent {

  componentDidMount () {

    if (!isLoaded()) {
      
      bootstrap((err) => {
        if (err) {
          console.error(err)
        }
      }, this.props.options)
    }
  }

  render () {
    return null;
  }
}

export default EsriLoaderContainer;
```

and then include it at the root component level

```js
render () {

  const options = {
    url: '//js.arcgis.com/3.20/'
  };

  return 
    <div>
      <EsriLoaderContainer options={options} />
```

then in the component that loads a map you don't need that bootstrapping so you can just use `dojoRequire` as you're doing the check in that function to either use require or wait for the script to finish loading,

**Comment by tomwayson** [comment]
Thanks @davetimmins, good idea.

Here's what I came up w/ yesterday:

https://github.com/tomwayson/esri-react-router-example/pull/27

That works, but as I mention above, seems like no components have been rendered when I start the preload.

If I understand your example, I'd include the `<EsriLoaderContainer>` component either at the bottom of each route's component (except maybe at the top of the map's route component) or in the app component, [maybe here](https://github.com/tomwayson/esri-react-router-example/pull/27/files#diff-060b1004ac6b4d8b72f9d1349c98a2d0R35), and that should ensure that something is rendered before the JSAPI starts loading, right?

I'll give that a go.

**Comment by tomwayson** [comment]
Like so?

https://github.com/tomwayson/esri-react-router-example/compare/preload...preload-timmins-style

**Comment by davetimmins** [comment]
Not quite, the only file that needs to mount the `EsriLoaderContainer` is App.js

```js
import React from 'react'
// NavLinkItem is a wrapper around react-router's Link component
// that sets the active class on the <li> around the current nav link
import NavLinkItem from './NavLinkItem'
import EsriLoaderContainer from './EsriLoaderContainer'

export default React.createClass({
  render () {

    const options = {
      url: '//js.arcgis.com/3.20/'
    };

    const currentPathname = this.props.location.pathname
    return <div>
      <EsriLoaderContainer options={options} />
      <nav className='navbar navbar-default navbar-static-top'>
        <div className='container-fluid'>
          <div className='navbar-header'>
            <a className='navbar-brand hidden-xs'>Esri React Router Example</a>
          </div>
          <ul className='nav navbar-nav no-collapse' role='nav'>
            <NavLinkItem to='/' currentPathname={currentPathname}>Home</NavLinkItem>
            <NavLinkItem to='/maps' currentPathname={currentPathname}>Maps</NavLinkItem>
          </ul>
        </div>
      </nav>
      <div className="main">
        { this.props.children }
      </div>
    </div>
  }
})
```

then the other file that needs changing is Map.js and that just needs to do

```js
componentDidMount () {
    
    this._createMap()
 }
```

**Comment by davetimmins** [comment]
Sorry I realized in my initial comment I mentioned including it for each route, should have said include it somewhere that is contained for each route i.e. the App component

**Comment by davetimmins** [comment]
Like this https://github.com/davetimmins/esri-react-router-example/commit/98f76987a4748e74dbdcc7379d7fdc06b332967b

**Comment by tomwayson** [comment]
Nice work @davetimmins - I put in a debugger and I can see that your way does indeed wait the components to be rendered before loading the JSAPI. See https://github.com/tomwayson/esri-react-router-example/pull/28
