### ISSUE TITLE
webpack errors and warnings when npm linked from ES2015 webpack app

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/esri-loader#2]
When I first tried to use this library via `npm link` in an [ES2015 app](https://github.com/tomwayson/esri-react-router-example/blob/bb57eae4cdbc935f8946f870683d3fd2603f7b68/modules/Map.js#L4) I was getting `Module build failed: Error: Couldn't find preset "es2015"` errors. Based on [this SO post](http://stackoverflow.com/questions/33711512/symlinking-react-modules-with-npm-link-for-local-development-gives-error) I was able to get past those by installing the package from the NPM registry. It looks like I could fix that by configuring webpack in the consuming app, but I wonder if there any settings that could be set on this end that would obviate that.

Once I got past those errors, I now see warnings in the webpack output in the terminal. The main one I'm concerned with as far as this library goes is:
```bash
WARNING in ./~/esri-loader/dist/index.js
Critical dependencies:
3:24-31 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/esri-loader/dist/index.js 3:24-31
```

I wonder if there's some way to to suppress that, or if it's better to leave it to let consuming apps know.

**Comment by davetimmins** [comment]
I had a go at getting this working in an existing app. I ran into errors which I've tracked down to using the `transform-runtime` plugin in the webpack babel loader config (could repro it with your react router example too).

**Comment by davetimmins** [comment]
Actually, scrap that. I had my webpack config set to output amd so removing that fixes it.

**Comment by davetimmins** [comment]
Here's a basic sample using the create-react-app starter. No longer needs to be ejected so much simpler to get going. https://github.com/davetimmins/create-react-app-esri-loader/

**Comment by tomwayson** [comment]
Resolved this in https://github.com/tomwayson/esri-react-router-example/commit/37dd6732f318dea163b28579661f192e4c0537a2
