### ISSUE TITLE
Enable using this library to pre-load the JSAPI

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/esri-loader#7]
Example:
1. user visits index route (no map, no JSAPI yet)
1. app renders index page, then starts loading JSAPI (`bootstrap()`) so that map route loads faster once people go there
1. user clicks link to map route
1. map route checks if already loaded (`isLoaded()`) _or loading_, if not, load JSAPI. Once JSAPI is loaded, create the map

The only thing new here (when compared to the lazy loading example) is keeping track of the notion that the JSAPI is already in the process of being loaded and providing a hook to do something once it's done. Currently users can pass a callback, but in a preloading scenario, the context is likely to change between when a user calls `bootstrap()`and when they want to actually create a map.

One idea is to expose an `isLoading` property and `.onLoad(fn)` (or `.on('load', fn)`) event. I'm not a real big fan of having _both_ a callback _and_ an event, so if we go this route, may want to deprecate the callback? Not sure.

Thoughts welcome.

**Comment by davetimmins** [comment]
It would be nice to use it as a promise similar to working with 4.x so something like 

```js
esriLoader({options}).then((require) => { 
  require(['esri/MapView'], (Map)) => {

    // do stuff here
  }
})
.otherwise( 
  // ruh roh 
);
```
Where it resolves to the require function.
That way it wouldn't matter what the internal state was to the user. It also means that you could remove `bootstrap` and `isLoaded` and probably `dojoRequire` since. Options could be a property rather than a parameter to prevent passing it each time.

**Comment by davetimmins** [comment]
Actually, even nicer would be to take it a step further and wrap the require internally so that it resolves to the modules requested

```js
esriLoader(['esri/MapView']).then((Map) => { 
  
  // do stuff here
})
.otherwise( 
  // ruh roh 
);
```

**Comment by tomwayson** [comment]
thanks @davetimmins. I've opened #8 as a place to discuss if/how to use promises.

I suppose promises could work for the preloading scenario above. The promise would have to be shared between routes, so:

```
// index route
app.esriLoaderPromise = esriLoader.bootsrtap(options);

// map route
if (app.esriLoaderPromise) {
  app.esriLoaderPromise.then(() => {/* create map */});
} else {
  esriLoader.bootsrtap(options).then(() => {/* create map */})
}
```

**Comment by davetimmins** [comment]
I was thinking more along the lines of just exposing the promise and the state is tracked internally, so the else statement above wouldn't be needed as it would equate to the internal promise being returned if already created. Does that make sense?

**Comment by tomwayson** [comment]
I think I get it, so:
```
// index route
// start pre-loading the JSAPI, but don't do anything once it loads
// this sets esriLoader._bootstrapPromise internally
esriLoader.bootsrtap(options);

// map route
// internally bootstrap() will check if _bootstrapPromise exits, if so, it'll return it
// which, in this case it will b/c it was called in the index route
// otherwise it would create a new promise and return that
esriLoader.bootsrtap(options).then(() => {/* create map */})
```

Is that what you are thinking?

**Comment by davetimmins** [comment]
Yea, so the public API is just one function and internally you have similar to what is in the current version but also a promise to track what state you are in.

**Comment by tomwayson** [comment]
Interesting. Still would have to figure out how to do #8 w/o adding yet another promise implementation to someone's app.

**Comment by alexurquhart** [comment]
First off thanks for putting these libraries up, I've just started playing with angular 2 and have been working off this to create a [similar implementation](https://github.com/alexurquhart/routecard/blob/master/src/app/services/esri-loader.service.ts) bundled in with an angular service.

One possible solution is to check for the existence of the API  script tag in `dojoRequire()`, and if `window['require']` is undefined, then add an event listener to the script that will execute the callback, like so:

In `bootstrap()`:

```javsscript
  // create a script object whose source points to the API
  const script = document.createElement('script');
  script.type = 'text/javascript';
  script.src = options.url;

  // Add data-attribute so we can find the script in dojoRequire()
  script.dataset.esriLoader = '';
```

`dojoRequire()`:
```
export function dojoRequire(modules: string[], callback: Function) {
  if (isLoaded()) { 
    window['require'](modules, callback);
    return;
  }
  
  const script = document.querySelector('script[data-esri-loader=""]');
  if (script) {
    // Not yet loaded but script is in the body - use callback after onLoad event
    script.addEventListener('load', () => {
      window['require'](modules, callback);
    });
  } else {
    // Not bootstrapped
    throw new Error('The ArcGIS API for JavaScript has not been loaded. You must first call esriLoader.bootstrap()');
  }
}
```

Here's a sample with some console.logs to demonstrate the order of operations: https://jsfiddle.net/gvaq4tph/4/
